### ISSUE TITLE
There's seems to be a bug in the StartTime formatted on Tasks in the API

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#1]

**Comment by danielqualitykitchen** [comment]
Keep up the good work!  Can't Stop Won't Stop

**Comment by mgpaja8** [comment]
I believe there is an bug when API is parsing StartTime property. From API response my opinion is that API doesnt receive StartTime (StartingAt) property with desired name.

**Comment by j0nscalet** [comment]
@mgpaja8 FYI so you're aware. In order to fix this I had to redeploy dev to our staging environment because we likely didn't have the newest version of the API there. Because the code was stale the API was stilling thinking it needed `Pattern.StartingAt` instead of `Pattern.StartTime`. 

Code was correct, this occurred because of a deployment problem. We've got to get continuous deployment back in place.
