### ISSUE TITLE
Setup nightly job to build tasks

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#17]
**Problem**
Checklists are generated once a day (nightly) for each operation in our platform. Tasks that need to be completed for the next day are generated from an Operation's task definitions.

We need to setup a nightly job to make an API call to build checklists. 

**Solution**
- This should be configured as an Azure job
- It should make an API call to 'Build Checklists' /operations/build/checklists
   - Per #8 this call should be updated to `POST /operations/{id}/checklists` to build checklists for a single operation
   - Note: we need to create an API call to build all checklists `POST /checklists`

**Comment by mgpaja8** [comment]
@j0nscalet  So right now API endpoint /tasks require DataTime object...

I do not know on top of my how to pass that object through Azure Scheduled Job.

Maybe solution is to have API determine current day + 1 and create tasks for next day?

Let me know what you think...
