### ISSUE TITLE
Setup Azure Job to call expire tasks every 1 minutes

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#34]
**Problem**
Setup and test azure scheduled job to call 'Expire Tasks' every 1 minute.

**Comment by j0nscalet** [comment]
@mgpaja8 I think you mentioned that you were going to remove the dependent parameter for this endpoint as well, right?

Right now it requires `dueBy` to be passed in. 
```
        [HttpPost("tasks/expire")]
        public IActionResult ExpireTasks()
        {
            // TODO We should remove BindResult in favor or letting ASP.net MVC
            // bind a request object [#20]
            BindResult<Dictionary<string, string>> bindResult = this.BindFromJson();

            string dueByTemp = bindResult.Model["dueBy"];
            DateTime dueBy = DateTime.Parse(dueByTemp);

            ServiceResult result = _taskApplicationService.ExpireTasks(dueBy);

            if (result.ResultCode == ServiceResult.ServiceResultCode.Failed)
                return this.ErrorResult(result);

            return this.SuccessResult(result);
        }
```
Like we did for 'Create All Tasks' let's remove 'dueBy' and use DateTime.Now.

**Comment by mgpaja8** [comment]
@j0nscalet  Exactly! Will be done soon!

**Comment by mgpaja8** [comment]
need to push #43 first and clean up staging database since its already messed up, before enabling this job again.

**Comment by j0nscalet** [comment]
Gotcha, added that as a dependency. (New ZenHub feature I wanted to try 💯)
