### ISSUE TITLE
API needs to support create tasks for all operations, not just one

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#36]
**Problem**
Currently the API only support creating (or building) tasks for a single operation  `POST /operations/{operationId}/task-definitions`. In order for #17 to work it'll need to support building tasks for all operations `POST /task-definitions`

**Solution**
This should be fairly straight forward to implement. We'll need to pass the `day` variable in the Request Body like we currently do then:
1.  Iterate through all operations
2. Get task definitions from the operation
3. Create tasks using the `TaskFactory'

- See: TaskApplicationService.TasksFromDefinitions for more details
- We still want to support the current endpoint that's in place, we'll likely still use it in dev
- We'll need to refactor logic in TaskApplicationService.TasksFromDefinitions to a private method and then call it from each endpoint. Like the `Assign - TaskApplicationService:227` method in TaskApplicationService.

**Comment by mgpaja8** [comment]
will do it as soon as when i get home

**Comment by j0nscalet** [comment]
@mgpaja8 One of just need to finish debugging this to figure out why it's using the same `Operationid` over and over.

**Comment by j0nscalet** [comment]
@mgpaja8 I know you're heads down on ListBuilder and I don't want you to shift focus right now. Do you think you'll have some additional bandwidth to knock this out afterwards? (We can debug it together if need be) What do you think?

**Comment by mgpaja8** [comment]
List builder will be done before I leave work, so we can huddle tonight to check it out and debug this issue. 
If you have time of course :) @j0nscalet

**Comment by j0nscalet** [comment]
@mgpaja8 yea dude for sure! Thanks so much for being someone I can lean on when we've got to deliver sprints. 🙏 We'll talk tonight. 👍

**Comment by danielqualitykitchen** [comment]
@mgpaja8 

Good job Pav!

**Comment by j0nscalet** [comment]
@mgpaja8 Would you mind tackling this? I know I was supposed to take a look but I cranking on the UI right now.

**Comment by mgpaja8** [comment]
@j0nscalet So we got this working, are you going to merge it to dev?

**Comment by j0nscalet** [comment]
@mgpaja8 There was no code changes to get it to work in staging. I'm still working on getting it to working in dev so tests pass.

I figured out what the issue is though. The local `OperationRepository` has logic that replaces the Operation if the same one exists in the collection. This delete the `TaskDefinitions` from that `Operation` and these us with 2 total definitions when they're should be 4.

See [OperationRespository:69](https://github.com/j0nscalet/QualityKitchen.API/blob/dev/src/QualityKitchen.Repositories.Local/OperationRepository.cs)

I tried to figure out a fix for it yesterday and got stuck. Glad it's working in staging but we've got to make sure all our tests pass. 

What do you think? Think you could put your eyes on it quick and see if you can resolve?

**Comment by mgpaja8** [comment]
@j0nscalet  will do it when get home

**Comment by j0nscalet** [comment]
@mgpaja8 👍

**Comment by j0nscalet** [comment]
@mgpaja8 Like we discussed updating this endpoint to determine the day instead of passing it will do the trick for Azure setup.

**Comment by j0nscalet** [comment]
@mgpaja8 this has been pushed to staging. I'm not sure how the API is going to react when we re-create tasks tomorrow since there's tasks that already exist. We shall see 👍

**Comment by j0nscalet** [comment]
@mgpaja8 How did this run last night? I know we're running into issues with employee Ids...just curious.
