### ISSUE TITLE
List Builder Fails to Bind _dayInterval in Hourly Pattern

### ISSUE THREAD

**Issue by mgpaja8** [j0nscalet/QualityKitchen.API#42]
**Problem**
[Describe the task/issue/bug in detail. This statement should be easily understandable]
When you call POST Create Task Definitions from List Builder (Google Sheets), API doesnt bind interval property.  That causes error : "Attempted to divide by zero"

![dayintervalerror](https://cloud.githubusercontent.com/assets/20258077/26119496/643e1f58-3a3b-11e7-8cac-8a89c1f720bd.PNG)

**Questions**
[List any questions that you have or need answered]
I am not sure if json that i am sending should contain _dayInterval or interval property.

**Solution**
[Describe potential solutions to the issue. For Design issues you should be writing code in this section]

**Comment by mgpaja8** [comment]
@j0nscalet I am not sure what was your idea when you were creating hourly pattern. Solution might be to hard code interval to 1 or add column to listbuilder where we will specify interval.

**Comment by j0nscalet** [comment]
@mgpaja8 Great job creating this issue. I can easily get an idea of what the issue is from the details you provide. That's the point.

A quick note: I'm glad that you used to placeholders in the 'Problem','Questions', and 'Solution' section, just remember to delete them when you're done.
