### ISSUE TITLE
ListBuilder should be able to import tasks when Daily and Hourly sheets are empty

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#47]
**Problem**
During our pilot program it's likely that Operation's will only be configured with 'Scheduled Tasks' and not 'Daily' or 'Hourly' tasks. For example let's say customer only wants to have a few tasks checked on Monday, Wednesday, and Friday at 9:00 AM and 9:05 AM. 

![image](https://cloud.githubusercontent.com/assets/1328795/26173003/27a946ca-3aff-11e7-9672-cfbf03e06151.png)

In this case 'Daily' and 'Hourly' sheet would be blank because they are not needed in this scenario. 

Currently if you try to 'Import' tasks with those two sheets empty you get the following error:

![image](https://cloud.githubusercontent.com/assets/1328795/26173062/5797db3a-3aff-11e7-8a9e-bbd7096eff7b.png)

If you open 'Script Editor' and run 'Import Tasks' in the 'Import.gs' file you'll get more details on the error and learn it's an issue with `SheetProcessor.gs:73`. 
Here's the code:
```
  /// getDataRows(sheet)
  /// Gets the data from a sheet, in most sheets in ListBuilder, data starts in row 3
  /// Arguments
  /// sheet - Sheet object
  /// dataStartsInRow - the row number that the data starts in the sheet
  /// Returns
  /// Object[][] - A two dimensional array of values
  _getDataRows : function(sheet, dataStartsInRow){
    var lastRow = sheet.getLastRow();
    var lastColumn = sheet.getLastColumn();
    return sheet.getRange(dataStartsInRow, 1, lastRow - dataStartsInRow + 1, lastColumn).getValues(); 
```
The call to `sheet.getRange` throws and error because the calculation of [`numOfRows`](https://developers.google.com/apps-script/reference/spreadsheet/sheet#getrangerow-column-numrows) is not valid. 

**Solution**
- Validation logic should be tweaked to ensure that at least one tab has data in it. In other words, at least one task definition (row) is required in: Daily, Hourly, or Scheduled Tasks tab.
- Doing this will ensure that we won't try to process a sheet that doesn't have any data

**Comment by j0nscalet** [comment]
@mgpaja8 I think `lastRow - dataStartsInRow + 1` is less than zero. That's why the error is being thrown. However, if we add the validation logic I'm proposing this shouldn't executing because we won't be trying to process a sheet that's empty. Make sense?

**Comment by mgpaja8** [comment]
Hey Jon it is throwing an error because lastRow - dataStartsInRow + 1 = 0.

This is solved by returning empty array if there is no data in the any sheet.

**Comment by j0nscalet** [comment]
@mgpaja8 baller! Yea I wasn't exactly sure.

Were you able to fix?

**Comment by mgpaja8** [comment]
@j0nscalet yeah its done.

you can test it and close this issue

**Comment by j0nscalet** [comment]
@mgpaja8 nice work dude 😎

**Comment by j0nscalet** [comment]
@mgpaja8 So you're aware we need to make sure that we setup 'Protected Sheet and Ranges' for users that want to create 'Scheduled Tasks'. Since you own 'ListBuilder v0.3.0.1, I can't access that option. I work around it by making a copy of the sheet. 

From the File Menu -> Data -> 'Protect sheet and ranges' and you should see this:
![image](https://cloud.githubusercontent.com/assets/1328795/26257600/1b72f068-3c76-11e7-9950-83e46c95ec36.png)

Notice that 'SummaryJson' range only has you (the owner) listed in permissions. We need to change that to 'People at Quality Kitchen'.

Make sense?
