### ISSUE TITLE
API endpoint to fetch tasks for an operation

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#5]
**Problem**
We need to be able to fetch tasks for an operation so we can expire tasks in the client.

**Questions**
[List any questions that you have or need answered]

**Solution**
- Add a new endpoint to our RestAPI (QualityKitchen.RestAPI) to fetch tasks given an operationId: /operation/tasks/{operationId}. 
Response:
A list of json serialized tasks, example:
```
[{
	stationId: "",
	shiftId: "",
	description: "",
	assignedTo: ""
	.
	.
	.
	dueBy: "9:00 AM"	
}]
```
- Rename /operation/tasks/all/{operationId} to something like: /operation/taskdefinitions/{operationId}. That name is needed to return tasks for the operation.
- Modify OperationApplicationService, add a method that will return a list of tasks for the operation
- Add a Tasks property to the Operation entity which will remove the need for the checklist entity

**Comment by j0nscalet** [comment]
Related issue - [Mobile #13](https://github.com/j0nscalet/QualityKitchen.Mobile/issues/13)

**Comment by mgpaja8** [comment]
I got this far and then realized we need Task table in db and Task entity in domain...

*** UPDATE ***

In RestAPI -> Controlers -> OperationControler:
1) Change HttpGet to operation/taskdefinitions/{operationId}

*** ADD ***
In Repositories.EfCore -> Repositories -> OperationRepository
1) Add method that gets all task for particular operation (operationId)

In Repositories.Local -> OperationRepository
1) Add method that gets all tasks for operation, local version


In Application ->  ApplicationServices -> IOperationApplicationService 
1) Add 
	ServiceResult<List<Task>> GetAllTasksForOperation(Guid operationId);

In Application -> ApplicationServices -> OperationApplicationService
1)Add
	public ServiceResult<List<Task>> GetAllTasksForOperation(Guid operationId)
	{
		try
           		 {
                			ThrowIf.GuidIsEmpty(operationId, nameof(operationId));

                			var allTasks = this._operationRepository.GetAllTasksForOperation(operationId).ToList();

                			return ServiceResult<List<Task>>.Success<List<Task>>(allTasks);
            		}
            		catch (Exception ex)
            		{
               			return ServiceResult.Fail<List<Task>>(ex);
           		}
	}



In RestAPI -> Controlers -> OperationControler:
1) Add 
	[HttpGet("operation/tasks/{operationId}")]
	public IActionResult GetAllTasksForOperation(string operationId)
	{
		Guid operationGuid = Guid.Empty;
           		 if (!Guid.TryParse(operationId, out operationGuid)) return this.ErrorResult("OperationId must be a valid Guid");

		ServiceResult<List<Task>> serviceResult = this._operationApplicationService.GetAllTasksForOperation(operationGuid);
		
		if(serviceResult.ResultCode == ServiceResult.ServiceResultCode.Failed) return this.ErrorResult(serviceResult);
		
		return this.SuccessResult(serviceResult);
	}

**Comment by j0nscalet** [comment]
@mgpaja8 This is awesome. Great way to begin to describe your solution approach. I'll respond in detail in a bit but just wanted to say great job. 👍 👍 💯

**Comment by j0nscalet** [comment]
@mgpaja8  here are my replies inline to your suggestions. Great job man.

>I got this far and then realized we need Task table in db and Task entity in domain... 

It's really good that you got here though. 

>*** UPDATE ***
>
>In RestAPI -> Controllers -> OperationController:
>1) Change HttpGet to operation/taskdefinitions/{operationId}

Remember we're talking about Tasks, not TaskDefinitions. They are two different things [read 'Domain Model' docs] to learn more.

The endpoint would be: /operation/tasks/{operationId}

>*** ADD ***
>In Repositories.EfCore -> Repositories -> OperationRepository
>1) Add method that gets all task for particular operation (operationId)

Spot on, the method could be called: 
```public List<Task> GetTasks(Guid operationId)```

>In Repositories.Local -> OperationRepository
>1) Add method that gets all tasks for operation, local version

Yup

>In Application ->  ApplicationServices -> IOperationApplicationService 
>1) Add 
>	ServiceResult<List<Task>> GetAllTasksForOperation(Guid operationId);

If I could suggest better naming here, the "all" was my mistake in the first place, so let's correct that with:
```ServiceResult<List<Task>> GetTasks(Guid operation)```

>In Application -> ApplicationServices -> OperationApplicationService
>1)Add
>	public ServiceResult<List<Task>> GetAllTasksForOperation(Guid operationId)
>	{
>		try
>          		 {
>                			ThrowIf.GuidIsEmpty(operationId, nameof(operationId));
>
>                			var allTasks = >this._operationRepository.GetAllTasksForOperation(operationId).ToList();
>
>              			return ServiceResult<List<Task>>.Success<List<Task>>(allTasks);
>            		}
>            		catch (Exception ex)
>            		{
>               			return ServiceResult.Fail<List<Task>>(ex);
>           		}
>	}

This kind of stuff is probably better to discuss in a pull request, but yea you're on the right track here. Fix the variable naming like above.

>In RestAPI -> Controllers -> OperationController:
>1) Add 
>	[HttpGet("operation/tasks/{operationId}")]
>	public IActionResult GetAllTasksForOperation(string operationId)
>	{
>		Guid operationGuid = Guid.Empty;
>           		 if (!Guid.TryParse(operationId, out operationGuid)) return >this.ErrorResult("OperationId must be a valid Guid");
>
>		ServiceResult<List<Task>> serviceResult = >this._operationApplicationService.GetAllTasksForOperation(operationGuid);
>		
>		if(serviceResult.ResultCode == ServiceResult.ServiceResultCode.Failed) return >this.ErrorResult(serviceResult);
>		
>		return this.SuccessResult(serviceResult);
>	}

Yup, spot on again. For design issues, it's enough to explain the solution approach with some pseudo code if needed. If you're going to write code you might as well put it in a feature branch and open a pull request. That way I can pull it and we can both look at the same thing.

**Comment by j0nscalet** [comment]
@mgpaja8 There's one more things to nail down on this design issue.

The structure of the Tasks table. Here's how I think we should structure it:
```
TABLE Task
--
_Id     int     auto_identity
OperationId uniquieidentifier
ShiftId uniqueidentifier
Station varchar(50)
Data varchar(max)
FK
OperatonId -> Operation.OperationId
```
[This link](https://github.com/j0nscalet/QualityKitchen.API#qualitykitchendatabase-database-project) will show you how to make changes to the database. You can't hurt anything in staging in production since you don't have access so don't be nervous! Go nuts. 😄 

This would be the start of a pretty big commit but like you said we can attack it together. Feel free to open a pull request if you need help along the way. Great work!

**Comment by j0nscalet** [comment]
@mgpaja8 Since we are tweaking the way that task expiration is going we won't need to elevate Task to an Aggregate anymore. 

Nonetheless, this was great work! Thanks for being such a team player. Onward and upward!
