### ISSUE TITLE
As a team member Incident Center needs to be re-organized

### ISSUE THREAD

**Issue by danielqualitykitchen** [j0nscalet/QualityKitchen.API#50]
AS A MANAGER:
 If something goes wrong, I need to know:“Who, what, where, when and why”  
WHO: employee, 
WHERE: shift and station 
What: What task was not able to be performed 
WHEN:  Date/Time   WHY: Why couldn’t it be done?  Did we take corrective actions?
WHY: Why couldn’t it be done?  Did we take corrective actions?

**Comment by danielqualitykitchen** [comment]
Update Bubble:  When a new comment is made or update made, a number should appear somewhere to quickly allow a manager to view incident center and see what has been updated.  Way better than clicking through each one.

**Comment by j0nscalet** [comment]
First row: Shift and Station, Severity, RelatedTask.Status
Second Row: Created Date
Third Row: Task
Fourth Row: Reason
Fifth: Last Updated By Jon Scalet and Number of Comments
