### ISSUE TITLE
Done Screen

### ISSUE THREAD

**Issue by danielqualitykitchen** [j0nscalet/QualityKitchen.API#54]
Still needed: will need undo button or delayed send and/or a toast

**Comment by mgpaja8** [comment]
@danielqualitykitchen  hey Danny, can you please provide description of issue so we know what is going on?

**Comment by j0nscalet** [comment]
@mgpaja8 He's just getting feedback inside GH right now so we can organize it later. No need to worry about these issues yet. 

@danielqualitykitchen You can convert these screen issues to 'Epics' and then add subsequent issues to the epic. Check [this out](https://www.zenhub.com/blog/working-with-epics-in-github/) for instructions. Should help us keep things even more organized. :)

**Comment by danielqualitykitchen** [comment]
Still needed:  will need undo button or delayed send and/or a toast

**Comment by danielqualitykitchen** [comment]
@mgpaja8  @j0nscalet 
Top of the morning boys!  How does this all look?

**Comment by mgpaja8** [comment]
@j0nscalet Oh okay, I didnt know.. 
@danielqualitykitchen Definitely features that will make app better :+1:
