### ISSUE TITLE
ListBuilder importing tasks doesn't update employee phone numbers properly

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#58]
**Problem**
After importing tasks with ListBuilder employee phone numbers aren't updated properly.

I attempted to send this data in the Employee Roster
![image](https://cloud.githubusercontent.com/assets/1328795/26258487/acb34e4e-3c79-11e7-809d-a02343ae2b95.png)

Here's what's available in the API after the call:
![image](https://cloud.githubusercontent.com/assets/1328795/26258499/be6f7766-3c79-11e7-9ff8-c4db441a5bc3.png)

Notice that employee phone numbers don't reflect what's in the 'Employee Roster' sheet. 

**Questions**
- Seems like (333)333-4444 is hard coded somewhere?

**Comment by j0nscalet** [comment]
@mgpaja8 Can you set an estimate (it's in minutes) when you get a chance on this? Trying to get back at being able to see how much work is left. Thanks bud.

**Comment by mgpaja8** [comment]
This is completed. Regex is added also to check is input matches pattern. You can close it. @j0nscalet
