### ISSUE TITLE
As an user, I want to know which tasks are time/temperature control and require a temp reading.

### ISSUE THREAD

**Issue by danielqualitykitchen** [j0nscalet/QualityKitchen.API#60]
**Problem**
As an user, I want to know which tasks are time/temperature control and require a temp reading.

**Questions**
With a temp high/low used in ListBuilder, will a thermometer auto populate

**Solution**
When a temp is required, a Thermometer icon should be in front of the task

**Comment by danielqualitykitchen** [comment]
![therem](https://user-images.githubusercontent.com/26260226/27344164-fe327afc-55aa-11e7-9614-d3a86d5050a4.png)

**Comment by danielqualitykitchen** [comment]
@j0nscalet   @mgpaja8 

This is how I visualize our user knowing a temp is required with a little thermometer next to expiration.  I like the incorporation of icons instead of words (as we know Jon runs a tight ship with words being used and I come from the school of Jon Scalet so the thermometer would be nice).

**Comment by mgpaja8** [comment]
@danielqualitykitchen I like icons as well, we can easily attach icons from here: http://fontawesome.io/icons/ 
@j0nscalet  im sure you heard for this icons.

**Comment by j0nscalet** [comment]
@danielqualitykitchen "school of Jon Scalet" 😃 

 A note about icons: we use [Google Material Icons](https://material.io/icons/), doing so makes sure that the look/feel stays consistent throughout our app. So let's choose an icon from there.

I love what you did with the wireframe here. It's exactly what we need to start doing to ensure we understand exactly what needs to be developed.

Ok, now for feedback. Let's move all icons over the left so they are consistent in the row. I think it will make it easier for the user to identify "Oh there's a spec and oh it reading a temperature reading".

What do you guys think?

**Comment by danielqualitykitchen** [comment]
Will this affect the margins of text?  Some tasks will have icons & info buttons and some will not.  This would create a weird look of the tasks not being in a single row


Example: (Let's use &! for I and Thermometer)
& ! Cold Holding: make sure the reach-in coolers are on at 40°F in the kitchen line
Ensure food in cooler is shielded or covered to protect it from contamination
& FIFO'ing in walk in cooler: Inspect in cooler when food was prepped to ensure newest product is behind older product

To me it would look best for the text to all be formatted to the left and have the icons on right, next to expiration.  Example would have the info button next to thermometer next to time expiration.  It will look cleaner that way.


Side note: There are no thermometers in the Material Icons :-1:

**Comment by j0nscalet** [comment]
@danielqualitykitchen man, great feedback. You nailed exactly what I was thinking right on the head, "in a  designated spot." That's what's important.

I'll plan on moving the "Info" and "Temp" icon (when we add it) to the right next to the time due.

**Comment by mgpaja8** [comment]
@j0nscalet so it is going to be on the left side of time due like in @danielqualitykitchen first picture?

**Comment by j0nscalet** [comment]
@mgpaja8 this is going to be your first solid issue when you're back from vaca next week so you're aware.

**Comment by danielqualitykitchen** [comment]
![checkin in as](https://user-images.githubusercontent.com/26260226/27752145-25e85d80-5da5-11e7-80f3-2bfd45d5922e.png)

**Comment by j0nscalet** [comment]
@mgpaja8 see if you can tackle this next. Read about DataTemplates for more info: https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/templates/data-templates/creating/

**Comment by mgpaja8** [comment]
![screen shot 2017-07-10 at 9 48 14 am](https://user-images.githubusercontent.com/20258077/28021210-237fba54-6555-11e7-9e69-91a5bc631bb2.png)

@danielqualitykitchen @j0nscalet 

Hey guys checkout this screenshot and let me know if I need to make any other changes. 
P.S. Danny, thunder icon will be replaced when we find one that suits our need. :)

**Comment by danielqualitykitchen** [comment]
@mgpaja8 

Great work!   This looks excellent.  Sounds good on the Thunder Icon.  We will want to use a thermometer icon of course.
