### ISSUE TITLE
Tasks object graph can grow exponentially and drastically affect app performance

### ISSUE THREAD

**Issue by mgpaja8** [j0nscalet/QualityKitchen.API#63]
**Problem**
I think that endpoint GET Tasks should return task filtered by that day or some kind of date. If we dont have this filter list of tasks is going to get so big very soon. 

**Solution**
Just add date parameter and endpoint to use POST method.

**Comment by j0nscalet** [comment]
@mgpaja8 great stuff. This was buried in TODOs that we haven't gotten to yet. Totally agree, if we don't filter than the payload is going to grow everyday and soon take quite some time for the app services to pull down.

We should probably rewrite the `TaskApplicationService.TasksBy` method to accept a query parameter as a `Func<Task, bool>` similar to `Find` in the Repositories.

```
        public ServiceResult<List<Task>> TasksBy(Guid operationId)
        {
            try
            {
                var tasks = _taskRepository.Find(t => t.OperationId == operationId).ToList();

                return ServiceResult<List<Task>>.Success<List<Task>>(tasks);
            }
            catch (Exception ex)
            {
                return ServiceResult<List<Task>>.Fail<List<Task>>(ex);
            }
        }
```
The method signature would be: `TaskBy(Func<Task, bool> query)` and we could support operations like:
`TasksBy(t => t.OperationId == operationId)`
or
`TasksBy(t => t.DueBy.Date == day)`

What do you think?

**Comment by j0nscalet** [comment]
As we suspected, here's a screenshot of a `GET /tasks` from staging earlier today, took 6.234 secs, definitely way too long. As you suggested @mgpaja8 filtering it by day will do the trick.
![image](https://user-images.githubusercontent.com/1328795/27059214-24b816c2-4f8a-11e7-8662-85d2325b5077.png)

**Comment by j0nscalet** [comment]
@mgpaja8 as we discussed yesterday this should be pretty straightforward. Let me know if you have any questions the solution approach.

**Comment by j0nscalet** [comment]
Here's the query details (SQL Performance Profiler) from Azure on the query:
![image](https://user-images.githubusercontent.com/1328795/27098950-162f9f68-502e-11e7-9ec5-a79ecd001eea.png)

I'll walk you through investigating a long running query in Azure on our next huddle.

**Comment by j0nscalet** [comment]
@mgpaja8 I gotta take this. I can't handle the 6s 'GET Tasks' query it's killing me.

**Comment by j0nscalet** [comment]
@mgpaja8 Sad news this doesn't improve performance of the 'Get Tasks' call at all 😢

**Comment by j0nscalet** [comment]
![image](https://user-images.githubusercontent.com/1328795/27382492-e28595b2-564c-11e7-86f8-4442adb6c6f9.png)

![image](https://user-images.githubusercontent.com/1328795/27382503-e93c577e-564c-11e7-9c27-cf1560b594d8.png)

**Comment by danielqualitykitchen** [comment]
@j0nscalet  Great work!  When does implement?  With the next build?

**Comment by j0nscalet** [comment]
@danielqualitykitchen This should already be pushed to our API staging environment and available in the app.
