### ISSUE TITLE
Task.Shift should be set based on the time a Task is due

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#68]
**Problem**
Currently, the Shift property of a Task is being hardcoded to AM. This is because we don't have a way to assign a Shift on a TaskDefinition in the API so as a workaround the value was hardcoded.

Looking at ListBuilder notice that there is no column for Shift
![image](https://user-images.githubusercontent.com/1328795/26937530-7bf9bc86-4c26-11e7-9722-990f7652ec5c.png)
Why is that? 
Initially we wanted managers to only focus on setting the time the task is due and not about particular shift window that fits it. We felt that it would be confusing over time so we wanted to devise something a bit easier to use. 

Instead, the API should use the Task.DueBy property to determine which shift the task should belong in.  For example, let's say an Operation has two shifts: AM (9:00 AM - 12:00PM) and PM (12:00 PM - 5:00 PM) and we define a Task in ListBuilder that's due at 4:30 PM. 

The subsequent Task should have it's Shift property set to AM since the task most naturally is due during the AM shift.

**Solution**
1. 
`TaskFactory:44`
```
        public static List<Task> CreateTasksFor(DateTime date, TaskDefinition definition, IEnumerable<Shift> shifts)
        {
            List<Task> tasks = new List<Task>();

            Shift shift = shifts.Where(s => s.Name == definition.Shift).SingleOrDefault();
```
Instead of simply querying for the `Shift` by name, we would need to add some logic that would query for the `Shift` based on the time the Task was DueBy, something like this:
```
Shift shift = shifts.where(s => s.StartTime >= definition.DueBy && definition.DueBy < s.EndTime).SingleOrDefault()  
```
- We'd have to remove the `Shift` property from TaskDefinition since it's no longer needed. As well as from the 'CreateTaskDefinition' API request in Postman
2. Ensure that all task definitions have dueBy times that are within a valid shift window. You shouldn't be able to define a TaskDefinition with a DueBy time of 6:00 PM in the above example.

**Comment by j0nscalet** [comment]
@mgpaja8 @danielqualitykitchen - let's discuss this. As I mentioned above we initially designed ListBuilder to be used by Managers but since have decided that it'll only be used by our team instead. 

While I think that this is a very doable change to implement, I'd rather take a minute and think through the ramifications before we dive in.

**Comment by j0nscalet** [comment]
@mgpaja8 @danielqualitykitchen we run into a bit of a issue with this approach when it comes to support pre-shift and post-shift tasks. At first glance we can solve that by extending the shift windows on both ends but I think that's short sided.

Let's say we have an operation with two shifts: AM (9:00 AM - 5:00 PM) and PM (5:00 PM - 10:00 PM) and a manager wanted to assigned post AM tasks on a few of the stations due at 5:15PM. If we could go down this path, these post AM tasks would be grouped in the PM shift. Not ideal.

At this stage I think the less restrictive we are the better until we get feedback from the wild. So here's what I'm advocating we do instead:
- Add a Shift column to 'Daily Tasks' and 'Scheduled Tasks' tab in ListBuilder
- No change to 'Hourly Duties', we'd still need to keep StartTime and EndTime around on Shift's so we can properly generate hourlies.

Doing so we'd be able to the following scenario: Breakfast - 7:30A-12:00P / Lunch - 12:00 P - 5:00P
Breakfast - Task 1 -  7:30 AM
Breakfast - Task 2 - 8:00 AM
Breakfast - Task 3 - 10:00 AM
Breakfast - Task 4 - 12:30 PM (With the approach we're discussing, this would be a Lunch task)

We could also support a Lunch employee starting while a Breakfast employee was finishing up, like:
Lunch- Task 1 - 12:00 PM
Breakfast - Task 4 - 12:30 PM

Or Lunch employee getting started early (which is really only semi-supported today). Let's say its: 11:00 A and the Lunch crew arrives early.

Breakfast - Task 4 -  12:30 PM
Lunch - Task 1 - 12:00 PM
Lunch - Task 2 - 12:30 PM

Notice we have a post-shift Breakfast task and a normal lunch Task due at the same time. We would not be able to support these scenarios in my original solution approach.

**Comment by j0nscalet** [comment]
NOTE: This would also mean tweaking Session timeouts as well. Instead of expiring sessions and signing employees out at the end of the Shift we would sign them out after the last task in the checklist is due.

**Comment by danielqualitykitchen** [comment]
@j0nscalet  @mgpaja8 

Jon, Thanks for really digging into this.  

Flexibility is key for our success because as we know restaurants are never black/white but grey.  In fact even the same restaurant concept in two different locations can have different shift times and etc.

I think adding a shift column would work just fine and actually would help with crossover of shifts.  EXAMPLE:
2 preps are scheduled for AM PREP but only one comes in to work.  The managers are banking on having 2 people complete this list and have assigned tasks accordingly.  In restaurants, the mantra is "THE SHOW MUST GO ON".  Guests do not care if a cook called in, they expect their prime rib damnit lol.    In this scenario, the The prep cook would be required to do 2 people’s tasks on that shift (not fun, I’ve done it).  IN this care this cook would stay way late past the normal shift time so allowing crossover would be great.
