### ISSUE TITLE
Cleanup API naming 

### ISSUE THREAD

**Issue by j0nscalet** [j0nscalet/QualityKitchen.API#8]
**Problem**
Our API endpoints are not consistent and should be.

**Comment by j0nscalet** [comment]
@jjvainav what do you think about this?

**Comment by jjvainav** [comment]
Here is a good resource that discusses naming conventions: http://www.restapitutorial.com/lessons/restfulresourcenaming.html

Firstly, I prefer to pluralize: /checklists/{id} - so if you break that down '/checklists' represents the whole collection and the id represents a specific item.

For the other verbs:

POST (create) -> /checklists
PUT (update) -> /checklists/{id}
DELETE (delete) -> /checklists/{id}

If you need to support access to parts of an object, you just build out the paths:

GET /incidents/{id}/details

**Comment by j0nscalet** [comment]
And if I need led to filter by a key like:
/checklists/{operationId}

Doing so bashed the {Id} option...thoughts?

**Comment by jjvainav** [comment]
It would depend on the relationship between checklists and operations. Is there a one-to-many relationship between operation -> checklist? If so, you could do /operations/{id}/checklists - where id is the operation id.

**Comment by j0nscalet** [comment]
thanks @jjvainav!

@mgpaja8 you might want to take a look at this stuff since you'll be tackling this.

**Comment by j0nscalet** [comment]
@jjvainav I think I know what you're going to say but if checklists are globally unique should we do:
/checklists/{Id}
or
/operation/{id}/checklists/{id}

In the domain while checklists are associated with an operation, they are globally unique. What do you think?

**Comment by jjvainav** [comment]
I think it makes sense to have /checklists/{id} but not the latter as they would both accomplish the same thing. 

There are a couple things to consider and this is where the client requirements may dictate what you would want to do. For instance:

- Should /operations/{id} pull down the entire object graph? If yes, you probably don't need /operation/{id}/checklists because you would already have all the data for that operation on the client.

- You may not want to pull down the entire object graph if - a) the data would be too large and/or b) much of the data would not be used. If this is the case, this is when you would make the additional calls to resources such as /operation/{id}/checklists to pull down all the checklists associated with the operation as needed.

**Comment by j0nscalet** [comment]
### API endpoints should be updated to the following:
[Postman collection](https://github.com/j0nscalet/QualityKitchen.API/blob/dev/QualityKitchen.Collection.json) for these calls would be good to reference and help all this make sense.

**Get Checklists**
- Change GET 'checklist/all/{operationId}' to /operations/{id}/checklists

**Pickup Checklist**
- Change `POST /checklist/pickup` to `/employee/check-in`
The request body doesn't change

**Flag Task**
- No change

**Complete Task**
- No change

**Expire Task**
- Change `POST /task/expire` to `POST /checklists/{id}/tasks/{id}/expire`

**Get All Incidents**
- Change 'GET /incident/all/{operationId}` to `GET /operations/{id}/incidents`

**Make Comment**
- Change 'POST /incident/comment/{operationId}' to `POST /employee/incident/comment`
The request body does not need to change, however you are not missing OperationId. That can be fetched the Incident entity.

**Fix (Incident)**
- Change `POST /incident/fix/{operationId}` to `POST /employee/incident/fix`
The request body doesn't change like 'Make Comment'.

**Resolve (incident)**
- Change `POST /incident/resolve/{operationId}` to `POST /manager/incident/resolve`
The request body doesn't change as above.

**SignIn**
- `POST /operations/{id}/signin` to `POST /employee/sign-in`
The request body does not change

**Get All Operations**
- `GET /operation/all/` to `GET /operations/{id}`

**Provision Operation**
- `POST /operation/provision` to `/provision/operation`
More naturally describes the action being taken

**Import Tasks**
-`POST /operation/import` to `PUT /operations/{id}`
Import came in because to update an operations details you use a tool to "import" it. It makes more sense for the API to update the operation using the PUT verb here.

**Build Checklists**
`POST /operation/build/checklists` to `POST /operation/{id}/checklists`
- This makes more sense since we are creating checklists for the operation in this call
- *NOTE In our model Checklists are creating from TaskDefinitions*

**Get TaskDefinitions**
-`GET /operation/tasks/all/{operationId}``GET /operations/{id}/task-definitions` 
*NOTE: Notice the hyphen in there for readability*

**Lookup by Device**
`GET /operation/lookup/{deviceId}` to `GET /operations/?deviceId={deviceId}`

### Other examples to reference
**Getting a single checklist**
- GET /operations/{id}/checklists/{checklistId} - Get single checklist for an operation by Id

**Filtering would look like this**
- `GET /operations/{id}/checklists/?task.status=active`
- `GET /incidents/?severity=minor` or `GET /incidents/?severity=critical`
*See: http://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/*

**Comment by danielqualitykitchen** [comment]
I'll set em' up... you just keep knocking em down!

@j0nscalet
